const { v4: uuidv4 } = require('uuid');
const db = require('../models/baseModel');
const permission = require('./permissionService');
const policy = require('./securityPolicyService');
const logService = require('./logService');
const STAGES = [['计划和确定项目',['客户需求','项目目标','可行性评审','初始材料清单','初始过程流程图','初始特殊特性清单','项目质量目标','项目计划']],['产品设计与开发验证',['设计评审','DFMEA','设计验证计划','设计验证结果','图纸或技术规范','工程变更记录','样件控制计划']],['过程设计与开发验证',['过程流程图','PFMEA','试生产控制计划','作业指导书','包装规范','设备和工装计划','测量系统计划','初始过程能力计划']],['产品和过程确认',['试生产记录','MSA 结果','初始过程能力研究','产品验证结果','过程验证结果','PPAP 提交状态','量产控制计划','生产准备评审']],['反馈、评定和纠正措施',['客户反馈','不良和投诉','8D 或整改任务','过程能力趋势','经验总结','遗留风险','项目关闭评审']]];
const now=()=>new Date().toISOString(); const history=(p,a,d,u)=>{db.prepare('INSERT INTO apqp_history VALUES(?,?,?,?,?,?,?)').run(uuidv4(),p.id,p.tenant_id,a,d,u.id,now()); logService.add({enterpriseId:p.tenant_id,userId:u.id,type:'apqp',title:a,detail:d});};
function project(id, tenant){return db.prepare('SELECT * FROM apqp_projects WHERE id=? AND tenant_id=?').get(id,tenant);}
function detail(p){const stages=db.prepare('SELECT * FROM apqp_stages WHERE project_id=? ORDER BY stage_no').all(p.id); return {...p,stages:stages.map(s=>({...s,deliverables:db.prepare('SELECT * FROM apqp_deliverables WHERE stage_id=?').all(s.id),risks:db.prepare('SELECT * FROM apqp_risks WHERE project_id=?').all(p.id),tasks:db.prepare('SELECT * FROM apqp_tasks WHERE stage_id=?').all(s.id),approvals:db.prepare('SELECT * FROM apqp_stage_approvals WHERE stage_id=?').all(s.id)}))};}
function create(input,u){permission.authorizeAgent({role:u.role}); const t=now(),id=uuidv4(),p={id,tenant_id:u.enterprise_id,project_no:String(input.project_no||`APQP-${Date.now()}`),project_name:String(input.project_name||'未命名 APQP'),customer_or_source:input.customer_or_source||'',product_description:input.product_description||'',project_owner:input.project_owner||u.name||'',project_team:input.project_team||'',project_type:input.project_type||'',importance_level:input.importance_level||'medium',planned_start_date:input.planned_start_date||'',planned_end_date:input.planned_end_date||'',customer_requirements:input.customer_requirements||'',special_requirements:input.special_requirements||'',created_by:u.id,created_at:t,updated_at:t}; db.prepare(`INSERT INTO apqp_projects(id,tenant_id,project_no,project_name,customer_or_source,product_description,project_owner,project_team,project_type,importance_level,planned_start_date,planned_end_date,customer_requirements,special_requirements,created_by,created_at,updated_at) VALUES(@id,@tenant_id,@project_no,@project_name,@customer_or_source,@product_description,@project_owner,@project_team,@project_type,@importance_level,@planned_start_date,@planned_end_date,@customer_requirements,@special_requirements,@created_by,@created_at,@updated_at)`).run(p); STAGES.forEach(([name,ds],i)=>{const sid=uuidv4();db.prepare('INSERT INTO apqp_stages(id,project_id,stage_no,name,status,progress,owner,start_date,due_date,approval_status,blocker_reason,next_step,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)').run(sid,id,i+1,name,'not_started',0,p.project_owner,'',p.planned_end_date,'not_required','','',t,t);ds.forEach(name=>db.prepare('INSERT INTO apqp_deliverables(id,project_id,stage_id,name,required,status,evidence_count,updated_at) VALUES(?,?,?,?,?,?,?,?)').run(uuidv4(),id,sid,name,1,'not_started',0,t));}); history(p,'创建 APQP 项目',p.project_no,u);return detail(project(id,u.enterprise_id));}
function evaluate(p,s){const ds=db.prepare('SELECT * FROM apqp_deliverables WHERE stage_id=?').all(s.id), tasks=db.prepare('SELECT * FROM apqp_tasks WHERE stage_id=?').all(s.id), risks=db.prepare("SELECT * FROM apqp_risks WHERE project_id=? AND level='high' AND status!='closed'").all(p.id);const missing=ds.filter(d=>d.required&&!d.evidence_count),open=tasks.filter(t=>t.status!=='completed');const approval=s.approval_status==='approved'||s.approval_status==='not_required';const total=ds.length+tasks.length+(s.approval_status==='not_required'?0:1);const done=ds.filter(d=>d.evidence_count).length+tasks.filter(t=>t.status==='completed').length+(s.approval_status==='approved'?1:0);return {ok:!missing.length&&!open.length&&!risks.length&&approval,progress:total?Math.round(done/total*100):0,reason:missing.length?'缺少交付物证据':open.length?'存在未完成任务':risks.length?'高风险未关闭':!approval?'审批未完成':''};}
function submit(pid,sid,u){permission.authorizeAgent({role:u.role});const p=project(pid,u.enterprise_id),s=db.prepare('SELECT * FROM apqp_stages WHERE id=? AND project_id=?').get(sid,pid);if(!p||!s)throw Error('项目或阶段不存在');const e=evaluate(p,s);db.prepare('UPDATE apqp_stages SET progress=?,status=?,blocker_reason=?,approval_status=?,updated_at=? WHERE id=?').run(e.progress,e.ok?'waiting_approval':'blocked',e.reason,e.ok?'pending':'not_required',now(),sid);if(e.ok)db.prepare('INSERT INTO apqp_stage_approvals VALUES(?,?,?,?,?,?,?,?,?)').run(uuidv4(),pid,sid,'pending',u.id,'','',now(),now());history(p,'提交阶段评审',e.reason||s.name,u);return detail(p);}
function decide(pid,sid,u,approved,reason=''){permission.authorizeApproval({role:u.role});const p=project(pid,u.enterprise_id),s=db.prepare('SELECT * FROM apqp_stages WHERE id=?').get(sid);if(!p||!s)throw Error('项目或阶段不存在');db.prepare('UPDATE apqp_stage_approvals SET status=?,decided_by=?,reason=?,updated_at=? WHERE stage_id=? AND status="pending"').run(approved?'approved':'rejected',u.id,reason,now(),sid);db.prepare('UPDATE apqp_stages SET status=?,approval_status=?,updated_at=? WHERE id=?').run(approved?'completed':'blocked',approved?'approved':'rejected',now(),sid); if(approved)db.prepare('UPDATE apqp_projects SET current_stage=MAX(current_stage,?),overall_progress=(SELECT AVG(progress) FROM apqp_stages WHERE project_id=?),updated_at=? WHERE id=?').run(s.stage_no+1,pid,now(),pid);history(p,approved?'审批通过':'审批驳回',reason,u);return detail(p);}
function must(id,u){const p=project(id,u.enterprise_id);if(!p)throw Error('项目不存在');return p;}
const PROJECT_UPDATE_FIELDS=Object.freeze(['project_name','customer_or_source','product_description','project_owner','project_team','project_type','importance_level','planned_start_date','planned_end_date','customer_requirements','special_requirements','risk_summary']);
const PROJECT_PROTECTED_FIELDS=Object.freeze(['id','project_no','tenant_id','current_stage','overall_progress','actual_end_date','status','version','created_by','created_at','updated_at']);
const PROJECT_HIGH_RISK_FIELDS=new Set(['project_owner','planned_end_date','importance_level']);
function updateProject(pid,input,u){const p=must(pid,u);permission.authorizeAgent({role:u.role});const forbidden=PROJECT_PROTECTED_FIELDS.filter(f=>Object.prototype.hasOwnProperty.call(input,f));if(forbidden.length){const e=new Error(`禁止直接修改字段：${forbidden.join('、')}`);e.status=400;throw e;}const fields=PROJECT_UPDATE_FIELDS.filter(f=>Object.prototype.hasOwnProperty.call(input,f));if(!fields.length){const e=new Error('没有可更新的项目字段');e.status=400;throw e;}if(fields.some(f=>PROJECT_HIGH_RISK_FIELDS.has(f)))permission.authorizeApproval({role:u.role});const values={id:pid,tenant_id:u.enterprise_id,updated_at:now()};for(const f of fields)values[f]=String(input[f]??'').trim();if(fields.includes('project_name')&&!values.project_name){const e=new Error('项目名称不能为空');e.status=400;throw e;}db.prepare(`UPDATE apqp_projects SET ${fields.map(f=>`${f}=@${f}`).join(', ')},version=version+1,updated_at=@updated_at WHERE id=@id AND tenant_id=@tenant_id`).run(values);history(p,'修改 APQP 项目',JSON.stringify({changes:fields.map(f=>({field:f,oldValue:p[f]??'',newValue:values[f]}))}),u);return {...detail(must(pid,u)),assessment:assessment(pid,u)};}
function evidence(pid,input,u){const p=must(pid,u);permission.authorizeAgent({role:u.role});const d=db.prepare('SELECT * FROM apqp_deliverables WHERE id=? AND project_id=?').get(input.deliverable_id,pid);if(!d)throw Error('交付物不存在');db.prepare('INSERT INTO apqp_evidence VALUES(?,?,?,?,?,?,?,?)').run(uuidv4(),pid,d.stage_id,d.id,String(input.file_name||'未命名证据'),String(input.note||''),u.id,now());db.prepare('UPDATE apqp_deliverables SET evidence_count=evidence_count+1,status="completed",updated_at=? WHERE id=?').run(now(),d.id);history(p,'上传证据',d.name,u);return detail(p);}
function risk(pid,input,u){const p=must(pid,u);permission.authorizeAgent({role:u.role});db.prepare('INSERT INTO apqp_risks VALUES(?,?,?,?,?,?,?,?)').run(uuidv4(),pid,String(input.title||'未命名风险'),input.level||'medium',input.status||'open',input.owner||'',now(),now());history(p,'新增风险',String(input.title||''),u);return detail(p);}
function task(pid,input,u){const p=must(pid,u);permission.authorizeAgent({role:u.role});const s=db.prepare('SELECT id FROM apqp_stages WHERE id=? AND project_id=?').get(input.stage_id,pid);if(!s)throw Error('阶段不存在');db.prepare('INSERT INTO apqp_tasks VALUES(?,?,?,?,?,?,?,?,?)').run(uuidv4(),pid,s.id,String(input.title||'未命名任务'),input.owner||'',input.status||'pending',input.due_date||'',now(),now());history(p,'新增任务',String(input.title||''),u);return detail(p);}
function close(pid,u,reason){const p=must(pid,u);permission.authorizeApproval({role:u.role});const stages=db.prepare('SELECT * FROM apqp_stages WHERE project_id=?').all(pid);const blocked=stages.map(s=>evaluate(p,s)).filter(x=>!x.ok);if(blocked.length)throw Error(`项目关闭被阻塞：${blocked[0].reason}`);db.prepare('UPDATE apqp_projects SET status="closed",actual_end_date=?,updated_at=? WHERE id=?').run(now(),now(),pid);history(p,'关闭项目',reason||'管理员确认',u);return detail(must(pid,u));}
function assessment(pid,u){const p=must(pid,u),stages=db.prepare('SELECT * FROM apqp_stages WHERE project_id=? ORDER BY stage_no').all(pid), checks=stages.map(s=>({stage:s,...evaluate(p,s)}));const blockers=checks.filter(x=>!x.ok).map(x=>({stage:x.stage.stage_no,reason:x.reason}));const progress=Math.max(0,Math.min(100,Math.round(checks.reduce((n,x)=>n+x.progress,0)/Math.max(1,checks.length))));return {current_stage:p.current_stage,overall_progress:progress,stage_progress:checks.map(x=>({stage_id:x.stage.id,stage_no:x.stage.stage_no,progress:x.progress,status:x.stage.status})),blockers,missing_deliverables:blockers.filter(x=>x.reason==='缺少交付物证据'),missing_evidence:blockers.filter(x=>x.reason==='缺少交付物证据'),incomplete_tasks:blockers.filter(x=>x.reason==='存在未完成任务'),open_high_risks:blockers.filter(x=>x.reason==='高风险未关闭'),pending_approvals:blockers.filter(x=>x.reason==='审批未完成'),next_actions:blockers.map(x=>x.reason),can_close_project:!blockers.length};}
function records(pid,u,type){must(pid,u);return db.prepare(`SELECT * FROM apqp_${type} WHERE project_id=?${type==='evidence'?' AND deleted_at IS NULL':''}`).all(pid);}
function update(pid,type,id,patch,u){const p=must(pid,u);permission.authorizeAgent({role:u.role});const allowed=type==='deliverables'?['status','owner','due_date','notes','is_applicable','not_applicable_reason']:type==='risks'?['title','description','severity','probability','impact','owner','due_date','mitigation','status','acceptance_reason','closure_evidence']:['title','description','owner','priority','due_date','status','completion_note'];const row=db.prepare(`SELECT * FROM apqp_${type} WHERE id=? AND project_id=?`).get(id,pid);if(!row)throw Error('记录不存在');if(type==='deliverables'&&patch.status==='completed'&&Number(row.evidence_count)<Number(row.required_evidence_count||1))throw Error('必交付物缺少证据');if(type==='risks'&&patch.status==='accepted'&&!(patch.acceptance_reason||row.acceptance_reason))throw Error('高风险接受必须填写理由');if(type==='risks'&&patch.status==='closed'&&!(patch.closure_evidence||row.closure_evidence))throw Error('关闭风险必须填写说明');if(type==='tasks'&&patch.status==='completed'&&row.evidence_required)throw Error('证据要求任务必须先关联证据');const fields=allowed.filter(k=>patch[k]!==undefined);if(!fields.length)return detail(p);const sql=fields.map(k=>`${k}=@${k}`).join(',')+',updated_at=@updated_at';db.prepare(`UPDATE apqp_${type} SET ${sql} WHERE id=@id`).run({...patch,id,updated_at:now()});history(p,`更新${type}`,JSON.stringify(fields),u);return detail(p);}
function removeEvidence(pid,id,input,u){const p=must(pid,u);permission.authorizeApproval({role:u.role});if(!input.delete_reason)throw Error('删除证据必须填写原因');const e=db.prepare('SELECT * FROM apqp_evidence WHERE id=? AND project_id=? AND deleted_at IS NULL').get(id,pid);if(!e)throw Error('证据不存在');db.prepare('UPDATE apqp_evidence SET deleted_at=?,deleted_by=?,delete_reason=? WHERE id=?').run(now(),u.id,input.delete_reason,id);db.prepare('UPDATE apqp_deliverables SET evidence_count=MAX(0,evidence_count-1),status=CASE WHEN evidence_count<=1 THEN "waiting_evidence" ELSE status END,updated_at=? WHERE id=?').run(now(),e.deliverable_id);history(p,'软删除证据',input.delete_reason,u);return detail(p);}
function historyList(pid,u){must(pid,u);return db.prepare('SELECT * FROM apqp_history WHERE project_id=? AND tenant_id=? ORDER BY created_at DESC').all(pid,u.enterprise_id);}
module.exports={STAGES,PROJECT_UPDATE_FIELDS,create,updateProject,detail:(id,u)=>({...detail(must(id,u)),assessment:assessment(id,u)}),list:u=>db.prepare('SELECT * FROM apqp_projects WHERE tenant_id=? ORDER BY updated_at DESC').all(u.enterprise_id).map(p=>({...p,assessment:assessment(p.id,u)})),submit,decide,evaluate,evidence,risk,task,close,history:historyList,assessment,records,update,removeEvidence};
