const { v4: uuid } = require('uuid');
const db = require('../database/client');
const runtime = require('./runtimeObservabilityService');
const approvalService = require('./approvalService');
const permissionService = require('./permissionService');

const TX_STATUSES = new Set(['PREPARING', 'WAITING_APPROVAL', 'EXECUTING', 'COMMITTED', 'ROLLED_BACK', 'CONCURRENCY_ABORT', 'FAILED', 'EXPIRED']);
const now = () => new Date().toISOString();
const json = value => JSON.stringify(value || {});
const parse = value => { try { return JSON.parse(value || '{}'); } catch { return {}; } };
function runFor(enterpriseId, userId, operationId) { return runtime.start({ enterprise_id: enterpriseId, user_id: userId, component_id: 'tool-registry', component_type: 'SKILL', task_type: 'mock_material_issue', trigger_source: 'transaction_preparation', provider: 'transaction-safety', runtime_or_model: 'deterministic-rule', execution_mode: 'DETERMINISTIC_RULE', input_summary: `模拟领料预检查：${operationId}` }); }
function auditAttempt({ run, stepId, attemptNo, status, code = '', message = '' }) { const id = uuid(); db.prepare('INSERT INTO runtime_attempts(id,run_id,step_id,enterprise_id,attempt_no,status,error_type,error_code,error_message,started_at,finished_at,duration_ms,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)').run(id, run.run_id, stepId, run.enterprise_id, attemptNo, status, code ? 'business_rule_error' : '', code, message, now(), now(), 0, now()); return id; }
function finishAttempt(id, status, error = {}) { db.prepare('UPDATE runtime_attempts SET status=?,error_type=?,error_code=?,error_message=?,finished_at=? WHERE id=?').run(status, error.code ? 'system_error' : '', error.code || '', error.message || '', now(), id); }
function auditValidation({ run, stepId, attemptId, result, input, reason = '', source = 'SNAPSHOT' }) { db.prepare('INSERT INTO runtime_validations(id,run_id,step_id,attempt_id,enterprise_id,validator_type,validator_version,schema_version,rule_id,rule_version,input_snapshot,validation_result,failure_reason,validation_source,stale_warning,override_allowed,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)').run(uuid(), run.run_id, stepId, attemptId, run.enterprise_id, 'BUSINESS_RULE_VALIDATOR', '1', '', 'inventory.non_negative_and_safety', '1', json(input), result, reason, source, source === 'SNAPSHOT' ? 'STALE_VALIDATION_WARNING: pre-approval data may change' : '', 0, now()); }
function preparationDetails(id, enterpriseId) { const preparation = db.prepare('SELECT * FROM transaction_preparations WHERE id=? AND enterprise_id=?').get(id, enterpriseId); if (!preparation) throw Object.assign(new Error('预检查不存在'), { status: 404 }); return { preparation, approval_card: parse(preparation.validation_result), transactions: db.prepare('SELECT * FROM business_transactions WHERE preparation_id=? AND enterprise_id=? ORDER BY execution_attempt').all(id, enterpriseId) }; }
function prepare({ enterpriseId, userId, role, input = {} }) {
  permissionService.authorizeAgent({ role });
  const operationId = String(input.business_operation_id || ''); const materialId = String(input.material_id || ''); const quantity = Number(input.quantity); if (!operationId || !materialId || !Number.isInteger(quantity) || quantity <= 0) throw new Error('business_operation_id、material_id 与正整数 quantity 必填');
  const active = db.prepare("SELECT * FROM transaction_preparations WHERE enterprise_id=? AND business_operation_id=? AND status IN ('PREPARING','WAITING_APPROVAL','APPROVED') ORDER BY created_at DESC LIMIT 1").get(enterpriseId, operationId); if (active) return { code: active.status === 'APPROVED' ? 'OPERATION_IN_PROGRESS' : 'WAITING_EXISTING_APPROVAL', ...preparationDetails(active.id, enterpriseId) };
  const inventory = db.prepare('SELECT * FROM mock_inventory WHERE material_id=?').get(materialId); if (!inventory) throw new Error('模拟物料不存在');
  const run = runFor(enterpriseId, userId, operationId); const stepId = uuid(); db.prepare('INSERT INTO runtime_steps(id,run_id,enterprise_id,step_no,name,status,retry_policy,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?)').run(stepId, run.run_id, enterpriseId, 1, 'Transaction Preparation', 'VALIDATING', json({ maxAttempts: 1, idempotent: false }), now(), now());
  const snapshot = { material_id: materialId, quantity, current_stock: inventory.current_stock, safety_stock: inventory.safety_stock, version: inventory.version }; const remaining = inventory.current_stock - quantity; const validator = { type: remaining < 0 ? 'STOCK_NEGATIVE' : remaining < inventory.safety_stock ? 'SAFETY_STOCK_FAILED' : 'PASSED', current_stock: inventory.current_stock, safety_stock: inventory.safety_stock, requested_quantity: quantity, remaining_stock: remaining, reason: remaining < 0 ? '库存不足，禁止领料' : remaining < inventory.safety_stock ? '库存低于安全库存，需要人工审批' : '预检查通过', validation_source: 'SNAPSHOT' };
  const attemptId = auditAttempt({ run, stepId, attemptNo: 1, status: 'SUCCESS' }); auditValidation({ run, stepId, attemptId, result: validator.type, input: snapshot, reason: validator.reason });
  const id = uuid(); const ttlMs = Math.max(60000, Math.min(86400000, Number(input.ttl_ms || 3600000))); const expiredAt = new Date(Date.now() + ttlMs).toISOString(); db.prepare('INSERT INTO transaction_preparations(id,enterprise_id,run_id,business_operation_id,snapshot_data,validation_result,created_at,expired_at,status) VALUES(?,?,?,?,?,?,?,?,?)').run(id, enterpriseId, run.run_id, operationId, json(snapshot), json(validator), now(), expiredAt, 'WAITING_APPROVAL');
  db.prepare('INSERT INTO agent_tasks(id,enterprise_id,user_id,agent_name,title,goal,status,current_step,total_steps,input_payload,output_payload,error_code,error_message,retry_count,confidence,needs_approval,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)').run(run.run_id, enterpriseId, userId, 'transaction-safety', '模拟领料审批', operationId, 'waiting_approval', 0, 1, json({ preparation_id: id, material_id: materialId, quantity }), '{}', '', '', 0, 0, 1, now(), now());
  const approval = approvalService.request({ taskId: run.run_id, enterpriseId, userId, toolName: 'mock_material_issue', actionLabel: '模拟库存领料', reason: validator.reason, payload: validator }); db.prepare('INSERT INTO runtime_approvals(id,run_id,enterprise_id,status,risk,reason,requested_by,created_at,updated_at,human_override,override_context) VALUES(?,?,?,?,?,?,?,?,?,?,?)').run(approval.id, run.run_id, enterpriseId, 'WAITING_APPROVAL', validator.type === 'PASSED' ? 'MEDIUM' : 'HIGH', validator.reason, userId, now(), now(), 0, json({ approval_card: validator }));
  db.prepare('INSERT INTO business_transactions(id,enterprise_id,business_operation_id,transaction_type,preparation_id,status,run_id,execution_attempt,lock_version,failure_reason,created_at,completed_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)').run(uuid(), enterpriseId, operationId, 'MOCK_MATERIAL_ISSUE', id, 'WAITING_APPROVAL', run.run_id, 1, inventory.version, '{}', now(), ''); runtime.finish(run.run_id, { execution_status: 'BLOCKED', verification_status: 'HUMAN_REVIEW_REQUIRED', error_code: 'waiting_approval', error_message: validator.reason }); return preparationDetails(id, enterpriseId);
}
function decide({ enterpriseId, actor, preparationId, approved, reason = '' }) { const detail = preparationDetails(preparationId, enterpriseId); if (detail.preparation.status !== 'WAITING_APPROVAL') throw new Error('预检查不在待审批状态'); const approval = db.prepare("SELECT * FROM runtime_approvals WHERE run_id=? AND enterprise_id=? AND status='WAITING_APPROVAL'").get(detail.preparation.run_id, enterpriseId); if (!approval) throw new Error('审批记录不存在'); approvalService.decide({ approvalId: approval.id, actor, approved, reason }); db.prepare('UPDATE runtime_approvals SET status=?,reason=?,decided_by=?,decided_at=?,updated_at=? WHERE id=?').run(approved ? 'APPROVED' : 'REJECTED', reason || approval.reason, actor.name || actor.userId, now(), now(), approval.id); if (!approved) { db.prepare('UPDATE transaction_preparations SET status=? WHERE id=?').run('EXPIRED', preparationId); db.prepare("UPDATE business_transactions SET status=?,completed_at=? WHERE preparation_id=? AND status='WAITING_APPROVAL'").run('ROLLED_BACK', now(), preparationId); runtime.finish(detail.preparation.run_id, { execution_status: 'CANCELLED', verification_status: 'NOT_VERIFIED', error_code: 'approval_rejected', error_message: reason || '审批拒绝' }); return preparationDetails(preparationId, enterpriseId); } db.prepare('UPDATE transaction_preparations SET status=? WHERE id=?').run('APPROVED', preparationId); db.prepare("UPDATE business_transactions SET status=? WHERE preparation_id=? AND status='WAITING_APPROVAL'").run('EXECUTING', preparationId); return preparationDetails(preparationId, enterpriseId); }
function execute({ enterpriseId, preparationId, simulateLedgerFailure = false }) {
  const detail = preparationDetails(preparationId, enterpriseId); const prep = detail.preparation; if (prep.status !== 'APPROVED') throw new Error('预检查尚未获批'); const run = { run_id: prep.run_id, enterprise_id: enterpriseId }; const step = db.prepare('SELECT * FROM runtime_steps WHERE run_id=? ORDER BY step_no LIMIT 1').get(prep.run_id); if (Date.now() > Date.parse(prep.expired_at)) { const attempt = auditAttempt({ run, stepId: step.id, attemptNo: detail.transactions.length + 1, status: 'FAILED', code: 'preparation_expired', message: '预检查快照已过期，请重新发起申请。' }); auditValidation({ run, stepId: step.id, attemptId: attempt, result: 'EXPIRED', input: parse(prep.snapshot_data), reason: '预检查快照已过期' }); db.prepare('UPDATE transaction_preparations SET status=? WHERE id=?').run('EXPIRED', preparationId); db.prepare('UPDATE business_transactions SET status=?,failure_reason=?,completed_at=? WHERE preparation_id=? AND status IN (\'WAITING_APPROVAL\',\'EXECUTING\')').run('EXPIRED', json({ code: 'preparation_expired' }), now(), preparationId); runtime.finish(prep.run_id, { execution_status: 'BLOCKED', verification_status: 'NOT_VERIFIED', error_code: 'preparation_expired', error_message: '预检查快照已过期，请重新发起申请。' }); return preparationDetails(preparationId, enterpriseId); }
  const previous = detail.transactions; let tx = previous.find(item => item.status === 'EXECUTING'); if (!tx) { const maxAttempt = previous.reduce((max, item) => Math.max(max, item.execution_attempt), 0); tx = { id: uuid(), execution_attempt: maxAttempt + 1 }; db.prepare('INSERT INTO business_transactions(id,enterprise_id,business_operation_id,transaction_type,preparation_id,status,run_id,execution_attempt,lock_version,failure_reason,created_at,completed_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)').run(tx.id, enterpriseId, prep.business_operation_id, 'MOCK_MATERIAL_ISSUE', preparationId, 'EXECUTING', prep.run_id, tx.execution_attempt, parse(prep.snapshot_data).version, '{}', now(), ''); }
  const snapshot = parse(prep.snapshot_data); const validator = parse(prep.validation_result); const audit = auditAttempt({ run, stepId: step.id, attemptNo: tx.execution_attempt, status: 'RUNNING' });
  try { db.exec('BEGIN IMMEDIATE'); const current = db.prepare('SELECT * FROM mock_inventory WHERE material_id=?').get(snapshot.material_id); const update = db.prepare('UPDATE mock_inventory SET current_stock=current_stock-?,version=version+1 WHERE material_id=? AND version=? AND current_stock-? >= 0').run(snapshot.quantity, snapshot.material_id, snapshot.version, snapshot.quantity); if (update.changes !== 1) { db.exec('ROLLBACK'); finishTx(tx.id, 'CONCURRENCY_ABORT', { code: 'optimistic_lock_conflict', expected_version: snapshot.version, current_version: current?.version }); finishAttempt(audit, 'FAILED', { code: 'optimistic_lock_conflict', message: '库存已变化，乐观锁检查失败' }); auditValidation({ run, stepId: step.id, attemptId: audit, result: 'CONCURRENCY_ABORT', input: { snapshot, current }, reason: '库存变化或版本冲突', source: 'READ_COMMITTED' }); runtime.finish(prep.run_id, { execution_status: 'FAILED', verification_status: 'FAILED_VERIFICATION', error_code: 'optimistic_lock_conflict', error_message: '库存已变化，未执行领料' }); return preparationDetails(preparationId, enterpriseId); }
    if (simulateLedgerFailure) throw new Error('simulated_ledger_failure'); db.prepare('INSERT INTO mock_material_ledger(id,transaction_id,material_id,quantity,created_at) VALUES(?,?,?,?,?)').run(uuid(), tx.id, snapshot.material_id, -snapshot.quantity, now()); db.prepare('UPDATE business_transactions SET status=?,completed_at=? WHERE id=?').run('COMMITTED', now(), tx.id); db.exec('COMMIT'); finishAttempt(audit, 'SUCCESS'); auditValidation({ run, stepId: step.id, attemptId: audit, result: 'PASSED', input: { snapshot, validator }, reason: '执行前重新验证通过', source: 'READ_COMMITTED' }); db.prepare('UPDATE transaction_preparations SET status=? WHERE id=?').run('COMMITTED', preparationId); runtime.finish(prep.run_id, { execution_status: 'SUCCESS', verification_status: 'VERIFIED' }); return preparationDetails(preparationId, enterpriseId);
  } catch (error) { try { db.exec('ROLLBACK'); } catch {} finishTx(tx.id, 'ROLLED_BACK', { code: error.message }); finishAttempt(audit, 'FAILED', { code: 'ledger_failed', message: '业务流水写入失败，库存已回滚' }); auditValidation({ run, stepId: step.id, attemptId: audit, result: 'ROLLED_BACK', input: snapshot, reason: '业务事务已回滚', source: 'READ_COMMITTED' }); runtime.finish(prep.run_id, { execution_status: 'FAILED', verification_status: 'FAILED_VERIFICATION', error_code: 'rolled_back', error_message: '业务流水失败，已回滚；审计记录已保留' }); return preparationDetails(preparationId, enterpriseId); }
}
function finishTx(id, status, reason) { if (!TX_STATUSES.has(status)) throw new Error('无效事务状态'); db.prepare('UPDATE business_transactions SET status=?,failure_reason=?,completed_at=? WHERE id=?').run(status, json(reason), now(), id); }
module.exports = { TX_STATUSES, prepare, decide, execute, preparationDetails };
